services:
  - type: web
    name: agrimaster-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_fastapi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
